services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    container_name: mp2-frontend
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ../MP2-B
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../MP2-B:/app
      - /app/node_modules
    env_file:
      - ../MP2-B/.env
    environment:
      - NODE_ENV=development
      - PORT=3000
    container_name: mp2-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge